# Generated by Django 4.1.5 on 2023-07-21 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
